const tableNames = {
  RolesDb: 'roles_db',
  UsersDb: 'users_db',
  AddressesDb: 'addresses_db',
  AdminsDb: 'admins_db',
  CouriersDb: 'couriers_db',
  PagesDb: 'pages_db',
  VerificationDb: 'verifications_db',
  SettingsDb: 'settings_db',
  SettingsHistoryDb: 'settings_history_db',
  CitiesDb: 'cities_db',
  CardsDb: 'cards_db',
  CountiesDb: 'counties_db',
  DistrictsDb: 'districts_db',
  OrdersDb: 'orders_db',
  PaymentsDb: 'payments_db',
  OrderStatuesDb: 'orderstatues_db',
  PreOrder: 'preorder_db',
  Promotions: 'promotions_db',
  BalanceDb: 'balance_db',
  OrderLogsDb: 'orderlogs_db',
  RequestDb: 'request_db',
  NotificationsDb: 'notifications_db',
  CourierLocationsDb: 'courier_locations_db',
};

module.exports = tableNames;
